baseURL = https://www.saucedemo.com
homeURL= https://www.saucedemo.com/inventory.html
appTitle = Swag Labs
errorMSG= Epic sadface: Username and password do not match any user in this service
errorMSG2= Epic sadface: Username is required
errorMSG3= Epic sadface: Password is required
