#Log files location add for external
property.basePath = test-outputs/logs

#Define the file appender
appender.file.type = File
appender.file.name = fileAppender
appender.file.fileName = ${basePath}/log_${date:yyyy-MM-dd_HH-mm-ss}.log
appender.file.layout.type = PatternLayout
appender.file.layout.disableAnsi=false
appender.file.filter.threshold.type=ThresholdFilter
appender.file.filter.threshold.level=debug
appender.file.layout.pattern = [%p] - %d{yyyy-MM-dd HH:mm:ss} [%t] [%c] - %msg%n

#Define the console appender
appender.console.type = Console
appender.console.name = consoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.disableAnsi=false
appender.console.filter.threshold.type=ThresholdFilter
appender.console.filter.threshold.level=debug
appender.console.layout.pattern = %highlight{[%p] - [%d{yyyy-MM-dd HH:mm:ss}] [%t] [%c] - %msg%n }{FATAL=red, ERROR=red, WARN=yellow, INFO=green, DEBUG=blue, TRACE=cyan}

#Configure the logger listen to eh
rootLogger= debug, fileAppender, consoleAppender
rootLogger.level = debug

